
if(NOT DEFINED LIB_DISPATCH_DIR)
  set(LIB_DISPATCH_DIR ${CMAKE_CURRENT_LIST_DIR})
endif()

set(LIB_DISPATCH_SOURCES
  "${LIB_DISPATCH_DIR}/lib_dispatch/src/task.c"
)

set(LIB_DISPATCH_INCLUDES
  "${LIB_DISPATCH_DIR}"
)